apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js
  labels:
    app: next-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-js-app
  template:
    metadata:
      labels:
        app: next-js-app
    spec:
      containers:
      - name: next-js-app
        image: iamabhiraj/next-js-application:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000

